# -*- coding: utf-8 -*-
"""Exercicio_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bO2wKDDMIAOIQpYWu5YLsotTO1xHuR7q
"""

def reverterString(texto):
    return texto[::-1]